// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/gain": {
            "get": {
                "description": "Este endpoint permite obter uma listagem de receitas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain"
                ],
                "summary": "Obter uma listagem de Receitas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "O número de registros retornados pela busca",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "A página que será buscada",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "O mês que será filtrado a busca",
                        "name": "month",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "O ano que será filtrado a busca",
                        "name": "year",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gservice.GainPaginateResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Este endpoint permite criar uma receita",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain"
                ],
                "summary": "Criar uma Receita",
                "parameters": [
                    {
                        "description": "Modelo de criação da receita",
                        "name": "gain",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gservice.CreateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/gservice.GainResponse"
                        }
                    }
                }
            }
        },
        "/v1/gain-projection": {
            "get": {
                "description": "Este endpoint permite obter uma listagem de receitas previstas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain-Projection"
                ],
                "summary": "Obter uma listagem de Receitas Previstas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "O número de registros retornados pela busca",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "A página que será buscada",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "O mês que será filtrado a busca",
                        "name": "month",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "O ano que será filtrado a busca",
                        "name": "year",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gpservice.GainProjectionPaginateResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Este endpoint permite criar uma receita prevista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain-Projection"
                ],
                "summary": "Criar uma Receita Prevista",
                "parameters": [
                    {
                        "description": "Modelo de criação da receita prevista",
                        "name": "gain_projection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gpservice.CreateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/gpservice.GainProjectionResponse"
                        }
                    }
                }
            }
        },
        "/v1/gain-projection/{id}": {
            "get": {
                "description": "Este endpoint permite obter uma receita prevista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain-Projection"
                ],
                "summary": "Obter uma Receita Prevista",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da receita prevista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gpservice.GainProjectionResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Este endpoint permite editar uma receita prevista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain-Projection"
                ],
                "summary": "Editar uma Receita Prevista",
                "parameters": [
                    {
                        "description": "Modelo de edição da receita prevista",
                        "name": "gain_projection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gpservice.UpdateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gpservice.GainProjectionResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Este endpoint permite remover uma receita prevista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain-Projection"
                ],
                "summary": "Remove uma Receita Prevista",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da receita prevista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gainprojection.ResponseDefault"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "status": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/gain-projection/{id}/create-gain": {
            "post": {
                "description": "Este endpoint permite realizar uma receita que foi prevista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain-Projection"
                ],
                "summary": "Realizar uma Receita Prevista",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da receita prevista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Modelo de criação da receita",
                        "name": "gain",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gpservice.CreateGainRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gpservice.GainResponse"
                        }
                    }
                }
            }
        },
        "/v1/gain/{id}": {
            "get": {
                "description": "Este endpoint permite obter uma receita",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain"
                ],
                "summary": "Obter uma Receita",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da receita",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gservice.GainResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Este endpoint permite editar uma receita",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain"
                ],
                "summary": "Editar uma Receita",
                "parameters": [
                    {
                        "description": "Modelo de edição da receita",
                        "name": "gain",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gservice.UpdateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gservice.GainResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Este endpoint permite remover uma receita",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain"
                ],
                "summary": "Remove uma Receita",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da receita",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gain.ResponseDefault"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "status": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gain.ResponseDefault": {
            "type": "object"
        },
        "gainprojection.ResponseDefault": {
            "type": "object"
        },
        "gpservice.CategoryResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "gpservice.CreateGainRequest": {
            "type": "object",
            "properties": {
                "pay_in": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "gpservice.CreateRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "pay_in": {
                    "type": "string"
                },
                "recurrence": {
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "gpservice.GainProjectionPaginateResponse": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "page_limit": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gpservice.GainProjectionResponse"
                    }
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "gpservice.GainProjectionResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/gpservice.CategoryResponse"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "pay_in": {
                    "type": "string"
                },
                "recurrence": {
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "gpservice.GainResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/gpservice.CategoryResponse"
                },
                "description": {
                    "type": "string"
                },
                "gain_projection_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "pay_in": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "gpservice.UpdateRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "pay_in": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "gservice.CategoryResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "gservice.CreateRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "pay_in": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "gservice.GainPaginateResponse": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "page_limit": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gservice.GainResponse"
                    }
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "gservice.GainResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/gservice.CategoryResponse"
                },
                "description": {
                    "type": "string"
                },
                "gain_projection_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "pay_in": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "gservice.UpdateRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "pay_in": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.0",
	Host:        "localhost:8080",
	BasePath:    "/api/",
	Schemes:     []string{},
	Title:       "Wallet Core",
	Description: "API que dispões de recursos para gerenciar as finanças pessoais",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
