// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/gain-projection": {
            "post": {
                "description": "Este endpoint permite criar uma receita prevista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain-Projection"
                ],
                "summary": "Criar uma Receita Prevista",
                "parameters": [
                    {
                        "description": "Modelo de criação da receita",
                        "name": "gain_projection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Informações do usuário em base64",
                        "name": "X-Userinfo",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.GainProjectionResponse"
                        }
                    }
                }
            }
        },
        "/v1/gain-projection/{id}": {
            "get": {
                "description": "Este endpoint permite obter uma receita prevista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gain-Projection"
                ],
                "summary": "Obter uma Receita Prevista",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da receita prevista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token de autenticação do usuário",
                        "name": "X-Access-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Informações do usuário em base64",
                        "name": "X-Userinfo",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.GainProjectionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.CategoryResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "service.CreateRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "pay_in": {
                    "type": "string"
                },
                "recurrence": {
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "service.GainProjectionResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/service.CategoryResponse"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_passive": {
                    "type": "boolean"
                },
                "pay_in": {
                    "type": "string"
                },
                "recurrence": {
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.0",
	Host:        "localhost:8080",
	BasePath:    "/api/",
	Schemes:     []string{},
	Title:       "Wallet Core",
	Description: "API que dispões de recursos para gerenciar as finanças pessoais",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
